#!/bin/bash

WALLPAPER_DIR="$HOME/Videos/wallpapers"
MONITOR="eDP-2"
STATE_FILE="$HOME/.hyprwall/Wallpaper_Dir.txt"

run_wallpaper() {
    local file="$1"
    mpvpaper -o "load-scripts=no no-audio --loop" "$MONITOR" "$file" &
}

stop_wallpaper() {
    pkill -x mpvpaper
}

if pgrep -x mpvpaper > /dev/null; then
    echo "haha"
    stop_wallpaper
else
    entries=""
    for file in "$WALLPAPER_DIR"/*; do
        base=$(basename "$file")
        thumb=$(mktemp /tmp/thumbXXXX.png)
        # Generate thumbnail at 1s mark, scale to ~384px width
        ffmpeg -y -i "$file" -ss 00:00:01 -vframes 1 -vf scale=384:-1 "$thumb" >/dev/null 2>&1
        entries+="${base}\0icon\x1f${thumb}\n"
    done

    selected=$(echo -en "$entries" | rofi -dmenu -p "Select Wallpaper" -show-icons -theme-str 'element-icon { size: 96; orientation: east; }')
    if [ -n "$selected" ]; then
        run_wallpaper "$WALLPAPER_DIR/$selected"
	echo "$selected" > "$STATE_FILE"
    fi
fi

